name: CI Pipeline

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_binaries:
    name: Build Binaries
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.8

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: |
          export PATH="$GOBIN:$PATH"
          . build.sh
        env:
          ARTIFACTS: ${{ runner.temp }}/artifacts
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: ${{ runner.temp }}/artifacts/binaries

  linux:
    name: Linux
    runs-on: ubuntu-20.04
    needs: build_binaries

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: artifacts/binaries

      - name: Run Docker Tests
        run: . run-docker-tests-linux.sh
        shell: bash

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
